import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, realpathSync, mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { hostVersion } from '../paseo-plugin/host/version.mjs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url);
const paseoRequire = createRequire(realpathSync(process.env.PATH.split(':').map(dir => join(dir, 'paseo')).find(existsSync)));
const serverEntry = paseoRequire.resolve('@getpaseo/server');
let root = dirname(serverEntry);
while (!root.endsWith('/@getpaseo/server') && dirname(root) !== root) root = dirname(root);
const { compilePlugin } = await import(pathToFileURL(join(root, 'dist/server/server/plugins/compiler.js')));
const { clientBundle } = await compilePlugin(resolve('paseo-plugin/index.ts'));
const pluginRequire = createRequire(resolve('paseo-plugin/package.json'));
const sdk = { useWorkspace() {}, useRpc() {} };
const evaluate = Function(`return ${clientBundle}`)();
const module = evaluate(name => {
  if (name === '@getpaseo/plugin') return sdk;
  if (name === '@getpaseo/plugin/server') return { defineRpc: x => x };
  if (name === 'react-native') return { Pressable: 'button', ScrollView: 'div', Text: 'span', View: 'div' };
  return pluginRequire(name);
});
const registrations = new Map();
const plugin = new Proxy({}, { get: (_, name) => (...args) => { registrations.set(name + ':' + (args[0]?.id ?? args[0]), args); } });
const cleanup = module.default(plugin);
assert.equal(typeof cleanup, 'function');
assert.ok(registrations.has('addSurface:architect'));
assert.ok(registrations.has('addWorkspacePanel:ticket'));
const command = registrations.get('addCommandCenterItem:start-architect')[0];
const called = [];
await command.onSelect({ workspace: { directory: '/selected/workspace' }, rpc: async (contract, input) => called.push({ name: contract.name, input }), openPanel: id => called.push(id) });
assert.deepEqual(called, [{ name: 'architect.start', input: { cwd: '/selected/workspace', title: 'Architect' } }, 'ticket']);
cleanup();
console.log('actual compiled client registers its panel and invokes workspace-scoped Start');
const fixture = mkdtempSync(join(tmpdir(), 'architect-server-bundle-'));
try {
  mkdirSync(join(fixture, 'host', 'providers'), { recursive: true });
  const nested = join(fixture, 'host', 'providers', 'model.mjs');
  writeFileSync(nested, 'export const revision = 1;');
  const original = hostVersion(join(fixture, 'host'));
  writeFileSync(nested, 'export const revision = 2;');
  assert.notEqual(hostVersion(join(fixture, 'host')), original, 'nested source changes must trigger a host upgrade');
  const entry = join(fixture, 'index.ts');
  writeFileSync(join(fixture, 'version.server.ts'), `export { hostVersion } from ${JSON.stringify(resolve('paseo-plugin/host/version.mjs'))};`);
  writeFileSync(entry, `import { hostVersion } from './version.server'; export default function contribute(plugin) { plugin.handle('version', hostVersion); }`);
  const { serverBundle } = await compilePlugin(entry);
  const bundled = Function(`return ${serverBundle}`)()(pluginRequire);
  let getVersion;
  bundled.default({ handle: (_contract, handler) => { getVersion = handler; } });
  assert.equal(getVersion(), hostVersion(), 'bundled and standalone hosts must identify the same source revision');
} finally { rmSync(fixture, { recursive: true, force: true }); }
