#!/usr/bin/env node
import assert from 'node:assert/strict';
import { assembleArchitectRequest, keptPairs, rememberPair, requestPairs, conversationTokens, contextWindow, CONVERSATION_TOKEN_FLOOR } from '../paseo-plugin/host/fold.mjs';
const history = Array.from({ length: 4 }, (_, i) => ({ messageId: `m${i}`, operator: `short ${i}`, architect: 'yes' }));
const original = structuredClone(history);
assert.equal(CONVERSATION_TOKEN_FLOOR, 0);
assert.deepEqual(requestPairs(history, 'ok'), history.slice(-1));
assert.deepEqual(keptPairs(history), history.slice(-2));
assert.deepEqual(contextWindow(requestPairs(history), 'now'), { userMessageIds: ['m3', 'now'] });
const huge = { messageId: 'big', operator: 'question', architect: ' word'.repeat(10000) };
assert.deepEqual(requestPairs([huge], 'ok'), [huge], 'two-turn retention has no arbitrary token cap');
const items = [{ role: 'user', content: 'original question' }, { type: 'reasoning', encrypted_content: 'opaque' }, { type: 'function_call', call_id: 'c', name: 'ticket_write', arguments: '{}' }, { type: 'function_call_output', call_id: 'c', output: 'result' }, { role: 'assistant', content: 'answer' }];
const next = rememberPair(history, 'original question', 'answer', 'next', items);
assert.equal(next.length, 2);
const request = assembleArchitectRequest({ pairs: JSON.parse(JSON.stringify(next)), ticketText: 'pinned', operatorText: 'continue' });
assert.deepEqual(request.input.slice(1, -1), items, 'complete prior exchange survives persistence and replay');
assert.equal(request.input.at(-1).content, 'continue');
assert.deepEqual(history, original);
assert.deepEqual(keptPairs(undefined), []);
assert.ok(conversationTokens('你好 <|endoftext|>') > 0);
console.log('Strict two-turn selection, complete reasoning/tool replay, persistence and no floor passed');
