[global]
    hostname = qq-box

[db]
    db = dbengine
    update every = 5
    dbengine tier 0 retention size = 256MiB
    dbengine tier 1 retention size = 256MiB
    dbengine tier 2 retention size = 256MiB

[web]
    bind to = 127.0.0.1:19999
    allow connections from = localhost
    allow dashboard from = localhost
    allow management from = localhost

[ml]
    enabled = no

[plugins]
    ebpf = no
    network-viewer = no
    slabinfo = no

[health]
    enabled = yes
    script to execute on alarm = /bin/true

[logs]
    access = off

[plugin:cgroups]
    script to get cgroup network interfaces = /bin/true
    run script to rename cgroups matching = !*
    enable by default cgroups matching = /user.slice/user-*/user@*.service/app.slice/*.service /system.slice/*.service *docker* !*
    cgroups to match as systemd services = /system.slice/*.service /user.slice/user-*/user@*.service/app.slice/*.service
