import { machine, release, type, version } from "node:os";

export const MINI_SWE_SYSTEM_PROMPT = "You are a helpful assistant that can interact with a computer.";

function systemInformation(info = {}) {
  return {
    system: info.system ?? type(),
    release: info.release ?? release(),
    version: info.version ?? version(),
    machine: info.machine ?? machine(),
  };
}

/** mini-swe-agent v2 instance prompt; completion is the done tool. */
export function renderMiniSweTask(task, info) {
  const os = systemInformation(info);
  return [
    `Please solve this issue: ${String(task ?? "")}`,
    "",
    "You can execute bash commands and edit files to implement the necessary changes.",
    "",
    "## Recommended Workflow",
    "",
    "This workflow should be done step-by-step so that you can iterate on your changes and any possible problems.",
    "",
    "1. Analyze the codebase by finding and reading relevant files",
    "2. Create a script to reproduce the issue",
    "3. Edit the source code to resolve the issue",
    "4. Verify your fix works by running your script again",
    "5. Test edge cases to ensure your fix is robust",
    "6. Run relevant tests as needed, then call `done`. Do not combine it with any other command. <important>After this, you cannot continue working on this task.</important>",
    "",
    "## Command Execution Rules",
    "",
    "You are operating in an environment where",
    "",
    "1. You issue at least one command",
    "2. The system executes the command(s) in a subshell",
    "3. You see the result(s)",
    "4. You write your next command(s)",
    "",
    "Each response should include:",
    "",
    "1. **Reasoning text** where you explain your analysis and plan",
    "2. At least one tool call with your command",
    "",
    "**CRITICAL REQUIREMENTS:**",
    "",
    "- Your response SHOULD include reasoning text explaining what you're doing",
    "- Directory or environment variable changes are not persistent. Every action is executed in a new subshell.",
    "- However, you can prefix any action with `MY_ENV_VAR=MY_VALUE cd /path/to/working/dir && ...` or write/load environment variables from files",
    "- Submit and finish by calling `done`. Do not combine it with any other command. <important>After this, you cannot continue working on this task.</important>",
    "",
    "Example of a CORRECT response:",
    "<example_response>",
    "I need to understand the structure of the repository first. Let me check what files are in the current directory to get a better understanding of the codebase.",
    "",
    '[Makes bash tool call with {"command": "ls -la"} as arguments]',
    "</example_response>",
    "",
    "<system_information>",
    `${os.system} ${os.release} ${os.version} ${os.machine}`,
    "</system_information>",
    "",
    "## Useful command examples",
    "",
    "### Create a new file:",
    "",
    "```bash",
    "cat <<'EOF' > newfile.py",
    "import numpy as np",
    'hello = "world"',
    "print(hello)",
    "EOF",
    "```",
    "",
    "### Edit files with sed:",
    "",
    ...(os.system === "Darwin" ? [
      "<important>",
      "You are on MacOS. For all the below examples, you need to use `sed -i ''` instead of `sed -i`.",
      "</important>",
      "",
    ] : []),
    "```bash",
    "# Replace all occurrences",
    "sed -i 's/old_string/new_string/g' filename.py",
    "",
    "# Replace only first occurrence",
    "sed -i 's/old_string/new_string/' filename.py",
    "",
    "# Replace first occurrence on line 1",
    "sed -i '1s/old_string/new_string/' filename.py",
    "",
    "# Replace all occurrences in lines 1-10",
    "sed -i '1,10s/old_string/new_string/g' filename.py",
    "```",
    "",
    "### View file content:",
    "",
    "```bash",
    "# View specific lines with numbers",
    "nl -ba filename.py | sed -n '10,20p'",
    "```",
    "",
    "### Any other command you want to run",
    "",
    "```bash",
    "anything",
    "```",
  ].join("\n");
}
